"""replace sharereceipt from model to join table

Revision ID: 544eb2450773
Revises: f4648208e23c
Create Date: 2025-10-05 20:42:59.309416

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '544eb2450773'
down_revision = 'f4648208e23c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('share_receipts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_share_receipts_receipt_id'))
        batch_op.drop_index(batch_op.f('ix_share_receipts_user_id'))
        batch_op.drop_column('share_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('share_receipts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('share_id', sa.INTEGER(), autoincrement=True, nullable=False))
        batch_op.create_index(batch_op.f('ix_share_receipts_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_share_receipts_receipt_id'), ['receipt_id'], unique=False)

    # ### end Alembic commands ###
