"""initial schema

Revision ID: f4648208e23c
Revises: 
Create Date: 2025-10-04 02:40:56.499322

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4648208e23c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dummy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('notifications',
    sa.Column('notification_id', sa.Integer(), nullable=False),
    sa.Column('from_user_id', sa.Integer(), nullable=True),
    sa.Column('to_user_id', sa.Integer(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['from_user_id'], ['users.user_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['to_user_id'], ['users.user_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('notification_id')
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_from_user_id'), ['from_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_to_user_id'), ['to_user_id'], unique=False)

    op.create_table('receipts',
    sa.Column('receipt_id', sa.Integer(), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=True),
    sa.Column('store_name', sa.String(length=255), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('image_base64', sa.Text(), nullable=True),
    sa.Column('ocr_text', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['users.user_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('receipt_id')
    )
    with op.batch_alter_table('receipts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_receipts_creator_id'), ['creator_id'], unique=False)

    op.create_table('items',
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('receipt_id', sa.Integer(), nullable=False),
    sa.Column('item_name', sa.String(length=255), nullable=True),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['receipt_id'], ['receipts.receipt_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('item_id')
    )
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_items_receipt_id'), ['receipt_id'], unique=False)

    op.create_table('share_receipts',
    sa.Column('share_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('receipt_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['receipt_id'], ['receipts.receipt_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('share_id'),
    sa.UniqueConstraint('user_id', 'receipt_id', name='uq_share_user_receipt')
    )
    with op.batch_alter_table('share_receipts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_share_receipts_receipt_id'), ['receipt_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_share_receipts_user_id'), ['user_id'], unique=False)

    op.create_table('transactions',
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.Column('from_user_id', sa.Integer(), nullable=True),
    sa.Column('to_user_id', sa.Integer(), nullable=True),
    sa.Column('receipt_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('status', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['from_user_id'], ['users.user_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['receipt_id'], ['receipts.receipt_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['to_user_id'], ['users.user_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('transaction_id')
    )
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transactions_from_user_id'), ['from_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_receipt_id'), ['receipt_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_to_user_id'), ['to_user_id'], unique=False)

    op.create_table('item_ownerships',
    sa.Column('ownership_id', sa.Integer(), nullable=False),
    sa.Column('receipt_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.item_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['receipt_id'], ['receipts.receipt_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ownership_id')
    )
    with op.batch_alter_table('item_ownerships', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_item_ownerships_item_id'), ['item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_item_ownerships_receipt_id'), ['receipt_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_item_ownerships_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item_ownerships', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_item_ownerships_user_id'))
        batch_op.drop_index(batch_op.f('ix_item_ownerships_receipt_id'))
        batch_op.drop_index(batch_op.f('ix_item_ownerships_item_id'))

    op.drop_table('item_ownerships')
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transactions_to_user_id'))
        batch_op.drop_index(batch_op.f('ix_transactions_receipt_id'))
        batch_op.drop_index(batch_op.f('ix_transactions_from_user_id'))

    op.drop_table('transactions')
    with op.batch_alter_table('share_receipts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_share_receipts_user_id'))
        batch_op.drop_index(batch_op.f('ix_share_receipts_receipt_id'))

    op.drop_table('share_receipts')
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_items_receipt_id'))

    op.drop_table('items')
    with op.batch_alter_table('receipts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_receipts_creator_id'))

    op.drop_table('receipts')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_to_user_id'))
        batch_op.drop_index(batch_op.f('ix_notifications_from_user_id'))

    op.drop_table('notifications')
    op.drop_table('users')
    op.drop_table('dummy')
    # ### end Alembic commands ###
